const serverHost = 'https://server.adefemiconsult.com/api/';
export function backEndLinks() {
    return{
        auth: serverHost+'auth/',
        refresh: serverHost+'auth/refresh/',
        user: serverHost+'user/',
        userProfile: serverHost+'user/profile/',
        userSearch: serverHost+'user/search/',
        userLog: serverHost+'user/log/',
        about: serverHost+'about/',
        portfolio: serverHost+'portfolio/',
        portfolioCapture: serverHost+'portfolio/captures/',
        portfolioHighlight: serverHost+'portfolio/highlight/',
        portfolioCategory: serverHost+'portfolio/category/',
        service: serverHost+'service/',
        skillset: serverHost+'skillset/',
        store: serverHost+'store/',
        storeReaction: serverHost+'store/reaction/',
        storeDownload: serverHost+'store/download/',
        storeCapture: serverHost+'store/capture/',
        storeHighlight: serverHost+'store/highlight/',
        storeCategory: serverHost+'store/category/',
        team: serverHost+'team/',
        blog: serverHost+'blog/',
        blogGenre: serverHost+'blog/genre/',
        blogTag: serverHost+'blog/tag/',
        blogComment: serverHost+'blog/comment/',
        blogReaction: serverHost+'blog/reaction/',
        blogCommentReaction: serverHost+'blog/comment-reaction/',
        blogView: serverHost+'blog/view/',
        passwordChange: serverHost+'password-change/',
        settingImage: serverHost+'page-setting/images',
        settingSocial: serverHost+'page-setting/socials',
        settingContact: serverHost+'page-setting/contact',
        mailEnquiry: serverHost+'make-enquiry',
    }
}
